### ISSUE TITLE
Suggestions of code refactoring to be more Pythonic

### ISSUE THREAD

**Issue by msaelices** [johnjaymoor/python-meeting-kata#1]
Hi! Good code example and test suite. I would only like to suggest you some changes to make it more pythonic:

* In general, avoid long names if possible. Python does not like to have `very_long_function_or_variable_names`. One trick is to take advantage of the namespacing. For example `os.path.join('tmp', 'foo.txt')`. Some example renaming I would suggest you:

    * Rename `free_calendar_slots_finder.py` to `meetings.py` or similar. By doing that, we could rename the functions inside because the module namespace is meaningful.
    * Rename `calculate_free_slots_for_meeting(...)` to something like `get_free_slots(...)`, with the previous suggestion about module renaming, the usage in a third party file would be something like `meetings.get_free_slots(...)`
    * etc.

* Prefix all the auxiliary functions not expected to be imported in a third-party code with the `_` prefix, and also with shorter names. E.g., `get_free_slots_in_calendar_base_on_meeting_duration(...)` to `_find_free_slots(...)`, as the rest of the name is not needed by looking at the passed arguments.

* Rename `unit_tests.py` to just `tests.py`, which is usually the convention. If you want to split the tests depending on the part you are testing, we usually name them `test_part1.py`, `test_part2.py`, and so on.

* If you want the `tests.py` file to be executable, which is good for automatizing the execution of the tests, you would need to add the following lines at the end of the file:

    ``` python
    if __name__ == '__main__':
        unittest.main()
    ```

* I think the two persons to meet would need to agree on only one daily bound, as their calendars already talk about their actual daily availability. So, the params number would be just `meetings.get_free_slots(calendar1, calendar2, daily_bounds)` and the code would be a little bit simpler.

* The `strtime_to_min(slot_time)` would be slightly more readable and Pythonic with this implementation (I would also rename to `_strtime_to_minute()` as min could be confused with minimum):

    ``` python
    def _strtime_to_minute(slot_time):
        hour, minute = slot_time.split(':')
        return int(hour) * 60 + int(minute)
    ```

* You can take advantage of the [destructuring assignments](https://medium.com/techtofreedom/5-best-practices-of-destructuring-assignments-in-python-81bce95c5fda) in some parts of the code, like this one:

    ``` python
    def _find_free_slots(calendar, daily_bounds, meeting_duration):
        free_slots = []
        start_time, end_time = daily_bounds
        for hour, minute in calendar:
            if _does_meeting_fit(start_time, hour, meeting_duration):
                free_slots.append([start_time, hour])
            start_time = minute
        if _does_meeting_fit(start_time, end_time, meeting_duration):
            free_slots.append([start_time, end_time])
        return free_slots
    ```

* To take advantage of all the operator overload in Python, I would create the class `Slot` and another class `Calendar` and override some built-in operators. Then you can use a lot of Python features that make the code much more readable. Actually, I've been tempted to do it in my personal meeting implementation. You can take a look: https://github.com/msaelices/python-examples/commit/ceb452d6963d631b91a8a3d632b6d630d191e10d

**Comment by johnjaymoor** [comment]
Changes applied
